apiVersion: v2
name: webredirect
version: 0.0.1alpha
description: A Helm chart to create web redirects using an Ingress in Kubernetes
home: https://anynines.github.io/helm-charts
sources:
  - https://github.com/anynines/helm-charts
maintainers:
  - name: Maximilian Mueller
    email: mmueller@anynines.com
    url: https://managed-services.anynines.com/
