apiVersion: v1
kind: Service
metadata:
  name: {{ include "webredirect.fullname" . }}
  labels:
    {{- include "webredirect.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  clusterIP: None
  selector:
    {{- include "webredirect.selectorLabels" . | nindent 4 }}
