name: check that Chart-README's are up-to-date

on:
  pull_request:
    paths:
      - 'charts/**'

jobs:
  helm-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Run helm-docs
        run: .github/helm-docs.sh
